version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip3 install -r requirement.txt
  build:
    commands:
      - python manage.py runserver
artifacts:
  files:
    - '**/*'
  name: hospital-artifact
  discard-paths: yes
