name: Django Docker CI/CD Workflow with Amazon ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: <your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: <your-aws-region>

    - name: Build Docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: <your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com/<your-repository-name>:latest

    - name: Push Docker image to Amazon ECR
      id: push-image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: <your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com/<your-repository-name>:latest
      env:
        ECR_REGISTRY: <your-aws-account-id>.dkr.ecr.<your-aws-region>.amazonaws.com
        ECR_REPOSITORY: <your-repository-name>
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: <your-aws-region>
